language: node_js
node_js:
- '16'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - main
deploy:
  provider: heroku
  app: plaksinalabjs
  on:
    branch: main
  api_key:
    secure: NuU/w65+4T7+QR7xiG0Dp2P7kUPQ3mU2r8fql7fl6WOFEXfhAOYy+5oMmlh6+cLi9jDf1rUZ6ly56BUMpVkbXD3pSa+2wOJnJZPvCoe7IevH4sUZcUMWPvUAsZe2YUkJcbn0zK+11jPwa4T/fTicWga/xk23alUL+AsqYMQO9K0Ear+1C1a23P+cPGRfZ5Mxa7sOorq25jrvxbJQnEBjfzRpgM0/p81l+/6NeN0P2aqeLI3oCmkHWQeRUpKVbaex0TcTXUkQgUc5bOJ59d5lxBsmaBMyJANYuEST9gz5tL43xsok2/tGR4j56ZByyt5Z3FAgPfV5f97YvO9FMxpcyjMwx9AagMe6gDtEnLiuxc+6MP1X317itVCQ/NyHmmUVaTnTNZHE7latftHjbRk3N0H5q63BB0kIehS9MesZEevapVE1/VtVfiM4c0vvASUgkp76i9FxBoz3PplhROzHpJTNb7gSUzkQ+bm83BkZd/epkmKofkYOoG9Y8fuhFogmTNZQUBo0dP8hCxEaBDdP6V1mK9PrZ65eyOtdyc0YFca5shiVFQBbgknCspbwPR3d+VvelSOzFE28Ht0edsP76mh0YFRIst1ecH7PT5M6QCw7g1rq8aontw03ElcJijyNzxf9UO4Xl1cibG+Yjje27dYPMOsqlVxPK5aDbGUi+FM=
script: echo "npm test temporarily disabled"
