language: node_js
node_js:
- '16'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - main

deploy:
  provider: heroku
  app: plaksinalabjs
  api_key:
    secure: C7NMRQzeqrcxnTrS15CiA8PRd0d0wNGWqnhLrkVmZGZrQADcBQCdAK10ZYs+ImSReC6BDAnl9RxPleEpP+rzMARPaORcUiSEbr55YAcTU4fo7PWxZPPO48OaF9GrLC0zWz+IwAcOa0lKs60bmP+ZIz0S5ciLuhaSZQS2O5p47iGL3CWSlVi7N9E2iBSTq0ojd8XF26Ht9Kt9wBjYcHm4OTBiltZGqIrcr9EM+8bn6+YAg/JqOL7Z0tn9SwjhcGo/Zsssjk5ktr/HTYxxZhalb3o5LDRKB38Mik+nQ/Zd7o2Bi/a5AlB2zSYMjhUV5bdzEgt4Dq83Ic41IbGw5+q5+RICPFDQ3501SPg3bbLjd55Jp0NSQ/hRANYES6vJd8REX3nRkeNi9exwN+2gUB1ugK/TAzSupoe1xhrk5KJYHEWgKsDAN5Zh65lNpJj2NE1toAyUBZ5fZxF7+/HTw1OnvItp0kGCwEt7oGdJpRBkxW2KUgFtC5ADRoR0svoZND/gg7Zcd0ixG06Jg81DoN7hyTxk+y15qWi0cE8p2d8eXH99lKUGbBAeLFir6VM5ZnQ59y6Syl+2PfDxp/2dmUkxYZZN8e+Q+hPVUX8baM2XQNX4WmCx4PPHbLBvnYmAJ0emDXCwUBR6R3QcJ5+whJQ3atOPHCI8I095rdUr5ED47OY=
